import Head from 'next/head'
import Footer from '../../components/layout/Footer'
import './globals.css'
import LayoutWrapper from '../../components/layout/LayoutWrapper'
import { GroupListContextProvider } from '../../contexts/UtilsContextUse'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Home</title>
      </Head>
      <body>

        <GroupListContextProvider>
          <LayoutWrapper>
            {children}
          </LayoutWrapper>
        </GroupListContextProvider>

        {/* <Footer/> */}
      </body>
    </html>
  )
}
