import Head from 'next/head'
import Footer from '../../components/layout/Footer'
import './globals.css'
import { Inter } from 'next/font/google'
import LayoutWrapper from '../../components/layout/LayoutWrapper'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Home</title>
      </Head>
      <body>

        <div >
          <LayoutWrapper>
            {children}
          </LayoutWrapper>

        </div>


        {/* <Footer
        facebook_link={''}
        twitter_link={''}
        google_link={''}
        linkedin_link={''}
        youtube_link={''}
      /> */}
      </body>
    </html>
  )
}
